services:
  globetalk_be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  globetalk_be_mysql:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=globetalk
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - MYSQL_TCP_PORT=3307
