services:
  globetalk_be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DOCKER_MYSQL_HOST=globetalk_be_mysql
      - DOCKER_MYSQL_DATABASE=globetalk
      - DOCKER_MYSQL_PORT=3307
      - DOCKER_MYSQL_USERNAME=user
      - DOCKER_MYSQL_PASSWORD=user123
    volumes:
      - ./src:/usr/src/app/src
  globetalk_be_mysql:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=globetalk
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
      - MYSQL_TCP_PORT=3307
  globetalk_be_redis:
    image: redis
    ports:
      - '6379:6379'
